### ISSUE TITLE
Kanban Setup Board

### ISSUE THREAD

**Issue by initseis** [smunozmo/ruby-group-capstone#46]
- [Github Project](https://github.com/smunozmo/ruby-group-capstone/projects/2)
- There are 4 members in our team

Assignments:
Team member 1 --> @sevinchek 
Team member 2 --> @the-catalystmc 
Team member 3 --> @hunter4466 
Team member 4 --> @smunozmo

**Comment by Davidosky007** [comment]
## Hi @sevinchek @the-catalystmc @hunter4466 @smunozmo 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 


![doing-good-gif](https://user-images.githubusercontent.com/52497246/137777872-4fffa5f2-385e-40b9-8890-0d1b2cb0e35e.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
